package by.praded.dependency_injection.container.impl;

import by.praded.dependency_injection.container.Provider;

/**
 * @author Kiryl Praded
 * 03.02.2021
 * <p>
 * Provider class that keeps an instance of class generated by {@link InjectorImpl}.
 */
public class ProviderImpl<T> implements Provider<T> {

    /**
     * Instance of class generated by {@link InjectorImpl}.
     */
    private T instance;

    /**
     * Class constructor
     *
     * @param instance - value for the field {@link ProviderImpl#instance}.
     */
    public ProviderImpl(T instance) {
        this.instance = instance;
    }

    /**
     * Method to get instance of generated class.
     *
     * @return value of {@link ProviderImpl#instance}.
     */
    @Override
    public T getInstance() {
        return instance;
    }
}
